"""Initial migration.

Revision ID: 8ac14fc46699
Revises: 
Create Date: 2024-06-14 02:24:45.489398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac14fc46699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('professor', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skip', sa.Boolean(), nullable=True))
        batch_op.alter_column('courseName',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('courseName',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('skip')
        batch_op.drop_column('info')
        batch_op.drop_column('year')
        batch_op.drop_column('professor')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
